cls
echo Take Command Setup
echo Extracting packages...
timeout 1 >nul
echo Installing...
timeout 6 >nul
echo Building packages...
timeout 3 >nul
echo Building uninstall module...
echo Building main executable...
echo Instalação completa!
pause >nul
